# The max length an item name can be. Set to -1 to disable.
maxItemNameLength: 100

# The max amount of lines a lore can have. Set to -1 to disable. (128 is the max amount of lines an item can have in Minecraft)
maxLoreLines: 10

# Set the message styles for each message type.
styles:
  default:
    accentColor: "#ba7cf8"
    prefix: "&8[<gradient:#ba7cf8:#ba7cf8>EssentialZ&8] "
  error:
    accentColor: "#FF1744"
    prefix: "&8[<#FF1744>‚ö†&8] "
  warning:
    accentColor: "#E9D502"
    prefix: "&8[<#E9D502>‚ö†&8] "
  success:
    accentColor: "#4CAF50"
    prefix: "&8[<#4CAF50>‚úî&8] "
  movement:
    accentColor: "#6EC6FF"
    prefix: "&8[<#6EC6FF>‚òÅ&8] "
  combat:
    accentColor: "#FF1A1A"
    prefix: "&8[<#FF1A1A>‚öî&8] "
  moderation:
    accentColor: "#8F9BFF"
    prefix: "&8[<#8F9BFF>‚òØ&8] "
  items:
    accentColor: "#FFD54F"
    prefix: "&8[<#FFD54F>üéí&8] "
  stats:
    accentColor: "#4CAF50"
    prefix: "&8[<#4CAF50>‚òÖ&8] "
  communication:
    accentColor: "#81C784"
    prefix: "&8[<#81C784>‚úâ&8] "
  teamchat:
    accentColor: "#FF8A65"
    prefix: "&8[<#FF8A65>üë•&8] "
  worldcontrol:
    accentColor: "#BA68C8"
    prefix: "&8[<#BA68C8>üåê&8] "